### ISSUE TITLE
Possible bug on inference/result_accumulators/instance_seg.py

### ISSUE THREAD

**Issue by chorongi** [Ali2500/TarViS#3]
https://github.com/Ali2500/TarViS/blob/85e5770d4f127c9e324cafb114c66c1ddf38dee7/tarvis/inference/result_accumulators/instance_seg.py#L133

```
self.previous_clip_frame_indices = frame_indices[num_overlap_frames:].tolist()
self.previous_clip_logits = mask_logits[:, num_overlap_frames:]
```

If I'm understanding correctly, this should be the following since we intend to store last `overlap_frames` predictions?

```
self.previous_clip_frame_indices = frame_indices[- num_overlap_frames:].tolist()
self.previous_clip_logits = mask_logits[:, - num_overlap_frames:]
```

Please correct me if I'm wrong. 
Thanks for sharing your amazing work!

**Comment by Ali2500** [comment]
Hi, 

Sorry for the late reply. I'm not able to debug code at this time, but did you try running your changed code with a frame overlap different to what is in the config? At the moment I think both versions will be the same since the frame overlap in the config is set to half of the clip length. If you could run inference on youtubs-vis/OVIS with a frame overlap of let's  say 3 then we'll know which is corect.
