### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by chen742** [Ali2500/TarViS#4]
Hi, authors

Thanks for your excellent work, 

I would like to know  where to download the pan_maps for coco, cityscapes and ade20k dataset, (/data/dataset_annotations/training/coco_panoptic/pan_maps/)

Thanks

**Comment by Ali2500** [comment]
Hi,

The panoptic maps have to be downloaded from the respective dataset websites e.g. for COCO download the 2017 training images + the 2017 panoptic annotations from here: https://cocodataset.org/#download

For cityscapes you'll have to register on the webiste to get the download links. For ADE20k you should download the earlier 2016 MIT Scene Parsing variant from here: http://sceneparsing.csail.mit.edu/

For cityscapes and ADE20k the folder containing the panoptic annotations may not be called "pan_maps" so just rename it to that.

**Comment by chen742** [comment]
Hi, 

Thanks for your prompt reply! It really helps. 

For ADE20k,  The downloaded file is ADEChallengeData2016, is that correct? 

For Cityscapes, could you pls tell me the name of the panoptic annotations?  I saw a few panoptic annotations on the official website. 

Thank you!

**Comment by Ali2500** [comment]
1) Yes the folder for ade20k is called ADEChallengeData2016
2) For cityscapes, you should download the 'gtFine' annotations and then convert them to the coco panoptic format by running the conversion script provided by the cityscapes authors: https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createPanopticImgs.py

For reference, in my directory I have 2975 training images in a single, flat directory named like `aachen_000000_000019_gtFine_panoptic.png`

![image](https://github.com/Ali2500/TarViS/assets/14821941/060090e3-a644-4dad-a182-86b6cf1eda82)

It's actually good that you brought this up because I did the data setup quite some time back and hence, forgot to document it in the readme. Let me know if this works or not.

**Comment by chen742** [comment]
Hi, 

Thanks for your detailed information, I think ade, cityscape and coco are clear for me, but to download Mapillary Vistas, I would like to know if you use 1.2 or 2.0 version, and if the panoptic maps are included in it? 

mapillary-vistas-dataset_public_v1.2.zip
mapillary-vistas-dataset_public_v2.0.zip

Thank you again for the help!

**Comment by Ali2500** [comment]
We actually used v1.2. The panoptic maps are included in the dataset zip at `mapillary/training/v1.2/panoptic`. Here there is no modification needed and you just need to link this folder to `${TARVIS_WORKSPACE_DIR}/dataset_annotations/training/mapillary_panoptic/pan_maps`.
