### ISSUE TITLE
issude about "Num failed tries:"

### ISSUE THREAD

**Issue by wengkai0** [Ali2500/TarViS#6]
Hi, 

Thanks for your open-source code! But I have the error below:

When I run "--model_dir my_first_tarvis_pretraining --cfg pretrain_resnet50_swin-tiny.yaml --amp  --cfg.MODEL.BACKBONE ResNet50" on a single GPU,  I got the below error, do you have any suggestion?
Num failed tries: 42
Num failed tries: 24
Num failed tries: 12
Num failed tries: 36
Num failed tries: 45
Num failed tries: 18
Num failed tries: 6
Num failed tries: 27
Num failed tries: 48
Num failed tries: 9
Num failed tries: 3

**Comment by Ali2500** [comment]
Hi,

This message is probably originating from here: https://github.com/Ali2500/TarViS/blob/main/tarvis/data/panoptic_image_dataset.py#L164

Can you add a print statement in the dataset class to check exactly which dataset is causing this (coco, mapillary, cityscapes or ade20k). `self.name` should contain this info. My guess is that the dataset annotations are somehow incorrectly setup. If the problem is coming from cityscapes please see this issue: https://github.com/Ali2500/TarViS/issues/4
